default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: Tours_development

test:
  <<: *default
  database: Tours_test

production:
  primary:
    <<: *default
    database: Tours_production
  cache:
    <<: *default
    database: Tours_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: Tours_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: Tours_production_cable
    migrations_paths: db/cable_migrate